import joblib

def clean_simple(text):
    return " ".join([word for word in text.lower().split() if len(word) > 2])

if __name__ == "__main__":
    print("📥 Loading real-world trained model artifacts from disk...")
    # These loads will look for the pkl files generated by your training step
    tfidf = joblib.load("tfidf_vectorizer.pkl")
    cat_model = joblib.load("category_model.pkl")
    prio_model = joblib.load("priority_model.pkl")

    # Feel free to change these test strings to see how the system routes them!
    test_tickets = [
        "My payment went through twice for the premium package, please refund the duplicate charge immediately.",
        "The login system is completely broken. Every time I hit enter, it displays a timeout connection error.",
        "Can you provide me with an invoice for my account subscription from last month?"
    ]

    print("⚙️ Running live multi-ticket batch inference...\n")
    for i, raw_ticket in enumerate(test_tickets, 1):
        cleaned = [clean_simple(raw_ticket)]
        vectorized = tfidf.transform(cleaned)
        
        pred_cat = cat_model.predict(vectorized)[0]
        pred_prio = prio_model.predict(vectorized)[0]
        
        print(f"🎫 Ticket #{i}: '{raw_ticket}'")
        print(f"   🏷️  Predicted Category : {pred_cat}")
        print(f"   🚨 Predicted Priority : {pred_prio}")
        print("-" * 60)